#!/bin/bash
#Loop through output of cat on text file containing all of the accession numbers
for acc in $(cat /home/sjb176/SRP/bash_scripts/SRR_Acc_List.txt)
do 
    #Run SRA toolkit to download accession files
    /home/sjb176/SRA/sratoolkit.3.0.2-ubuntu64/bin/fastq-dump $acc --split-files --outdir /home/SRP/testing/
done 

