#!/bin/bash
#
#PBS -N prinseqtest
#PBS -l walltime=8:00:00
#PBS -l vmem=32gb
#PBS -l nodes=1:ppn=16
#PBS -m bea
#PBS -M drt15@student.le.ac.uk

# Set OMP_NUM_THREADS for OpenMP jobs
export OMP_NUM_THREADS=$PBS_NUM_PPN



# Execute the job code
for file in /scratch/spectre/d/drt15/SRP/output/*_[1,2].fastq; do
    perl /scratch/spectre/d/drt15/SRP/prinseq_test/prinseq-lite-0.20.4/prinseq-lite.pl -fastq $file -min_len 30 -trim_left 10 -trim_qual_right 25 -lc_method entropy -lc_threshold 65 -out_format 3 
    	

done
