#!/bin/bash
#
#PBS -N FastQC
#PBS -l walltime=8:00:00
#PBS -l vmem=32gb
#PBS -l nodes=1:ppn=16
#PBS -m bea
#PBS -M drt15@student.le.ac.uk

# Set OMP_NUM_THREADS for OpenMP jobs
export OMP_NUM_THREADS=$PBS_NUM_PPN



# Execute the job code
for file in /scratch/spectre/d/drt15/SRP/output/*_[1,2].fastq; do
    perl /scratch/spectre/d/drt15/SRP/FastQC/fastqc $file --extract --outdir=/scratch/spectre/d/drt15/SRP/prinseq_test/results/testresnew
    	

done
